### ISSUE TITLE
On Android sharing to Instagram doesn't work

### ISSUE THREAD

**Issue by avseverin** [natsuite/NatShare-API#78] opened 2020-01-27 21:35 UTC
Platform: Android 10 (One UI 2.0)
Device: Samsung Galaxy S10+
NatShare version 1.2.1
Unity 2018.3.14f1

Tried sharing video (taken with NatCorder) and images. Checked with apps like Whatsapp, Facebook, Twitter, Gmail, Dropbox. Didn't have problems with those platforms. However sharing to Instagram feed opens Instagram with nothing to share, while attempting to share to Instagram story does nothing at all and returns to the original app. The problem with Instagram is only present when using  NatShare. Didn't test on iOS yet.

**Comment by Liam-Fologram** [comment] 2020-02-20 22:32
@olokobayusuf I believe this is caused by the same issue thats causing issue #80 that I reported. It's the same phone I had issues committing payloads with.

**Comment by olokobayusuf** [comment] 2020-03-19 15:36
Based on #80, 379ec036890bd69b17f242feb59cb7f8e5884e0a should fix this. Closing for now.

**Closed by olokobayusuf** 2020-03-19 15:36 UTC
Labels: android, bug
