### ISSUE TITLE
[iOS] Error when sharing on iOS devices

### ISSUE THREAD

**Issue by MeneghettiRS** [natsuite/NatShare-API#81] opened 2020-02-20 13:03 UTC
Hi!

I'm having some issues when sharing from an iOS device (Android works). The info.plist have the necessary additions stated in the ReadMe. I'll share below the devices I've tested with and the error I get in xCode:

Devices:
 - iPhone 8 plus iOS 13.3.1
 - iPad Pro 11' 13.3

Error:

`/var/mobile/Containers/Data/Application/FD8E4308-DCF7-4F95-AA5D-F729FEE25E27/Documents/Screenshots/Sanofi RA/photo_8.png
2020-02-20 09:43:17.769074-0300 ra[1507:410648] Adding image to gallery.
Screenshot created : /var/mobile/Containers/Data/Application/FD8E4308-DCF7-4F95-AA5D-F729FEE25E27/Documents/Screenshots/Sanofi RA/photo_8.png
Stopping Smart Terrain.
Stopping Device Tracker
Stopping Positional Device Tracker.
Stop Vuforia Engine
2020-02-20 09:43:26.175757-0300 ra[1507:410648] INFO/AR(1507) 2020-02-20 09:43:26: Vuforia paused.
2020-02-20 09:43:26.225118-0300 ra[1507:410648] [LayoutConstraints] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x280cbb070 LPLinkView:0x144135d00.leading == UILayoutGuide:0x281401ea0'UIViewLayoutMarginsGuide'.leading   (active)>",
   "<NSLayoutConstraint:0x280cbb6b0 H:[LPLinkView:0x144135d00]-(59)-| (active, names: '|':_UIActivityContentTitleView:0x144134b00 )>",
   "<NSLayoutConstraint:0x280cbe300 H:|-(0)-[_UIActivityContentTitleView:0x144134b00] (active, names: '|':_UINavigationBarContentView:0x144110570 )>",
   "<NSLayoutConstraint:0x280cbd400 _UIActivityContentTitleView:0x144134b00.trailing == _UINavigationBarContentView:0x144110570.trailing   (active)>",
   "<NSLayoutConstraint:0x280c867b0 'UIView-Encapsulated-Layout-Width' _UINavigationBarContentView:0x144110570.width == 0   (active)>",
   "<NSLayoutConstraint:0x280cb9ea0 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x281401ea0'UIViewLayoutMarginsGuide'](LTR) (active, names: '|':_UIActivityContentTitleView:0x144134b00 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x280cbb070 LPLinkView:0x144135d00.leading == UILayoutGuide:0x281401ea0'UIViewLayoutMarginsGuide'.leading   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.`

When I was using the 1.1f3 version it worked just fine. I've updated the plugin, modified the codes needed and then tested on Android, where it worked just fine. Can you help?

Thanks!

**Comment by olokobayusuf** [comment] 2020-02-20 13:24
Duplicate of #75

**Closed by olokobayusuf** 2020-02-20 13:24 UTC
